### ISSUE TITLE
reactive-pg-client typing to strict

### ISSUE THREAD

**Issue by marcust** [marcust/jzenith#2]
jOOQ believes that a offset/limit are int, reactive-pg-client believes they are long.

**Comment by marcust** [comment]
Opened as https://github.com/reactiverse/reactive-pg-client/issues/180

**Comment by marcust** [comment]
Opened as https://github.com/reactiverse/reactive-pg-client/issues/179

**Comment by vietj** [comment]
not the right issue

**Comment by marcust** [comment]
Resolved by the new release of reactive-pg-client
